apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: redis-statsd
  labels:
    app: {{ template "Chart.name" . }}
    chart: {{ template "Chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ["extensions"]
    resources: ["services"]
    verbs: ["list"]
