apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mountie
  labels:
    app: {{ template "Chart.name" . }}
    chart: {{ template "Chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: {{ template "Chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: redis-statsd
      containers:
        - name: app
          image: {{ .Values.image.repository }}/redis-statsd:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "./redis-statsd.py" ]
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
