apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-statsd
  labels:
    app: {{ template "Chart.name" . }}
    chart: {{ template "Chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
